# Generated by Django 4.0.6 on 2022-07-10 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0003_weatherdb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherdb',
            options={'verbose_name_plural': 'data'},
        ),
    ]
