# Generated by Django 4.0.6 on 2022-07-10 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0004_alter_weatherdb_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='WeatherDB',
        ),
    ]
